### ISSUE TITLE
Can not build vonuvoli on macos

### ISSUE THREAD

**Issue by bentxt** [volution/vonuvoli-scheme#102]
Hi,

cargo -V
cargo 1.58.0

I can not build vonuvoli on macos, here's the error I'm getting:

~~~~~~~~~~
 Compiling rand_chacha v0.2.2
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/bkb/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-rfc-0.2.18/src/lib.rs:19:31
   |
19 | #![cfg_attr(feature = "simd", feature(platform_intrinsics, repr_simd))]
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/bkb/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-rfc-0.2.18/src/lib.rs:20:35
   |
20 | #![cfg_attr(feature = "simd_opt", feature(cfg_target_feature))]
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
   |
   = help: the feature `cfg_target_feature` has been stable since 1.27.0 and no longer requires an attribute to enable

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/bkb/.cargo/registry/src/github.com-1ecc6299db9ec823/blake2-rfc-0.2.18/src/lib.rs:21:35
   |
21 | #![cfg_attr(feature = "simd_asm", feature(asm))]
   |                                   ^^^^^^^^^^^^

   Compiling lmdb-zero v0.4.4
   Compiling pulldown-cmark v0.8.0
For more information about this error, try `rustc --explain E0554`.
error: could not compile `blake2-rfc` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

~~~~~~~~~~~~~

**Comment by cipriancraciun** [comment]
First off thank you for the interest!

At the moment `vonuvoli` requires a nightly Rust compiler due to some unstable features that are used.  (Actually this was the situation 2 years ago, and in the meantime maybe they have been promoted into stable;  I'll have to check.)

I'll have a look at what it means to build it "today", perhaps even with the current stable compiler and report back.

Also I didn't try to build it on OSX, I use Linux for development, thus it might require some back-and-forth until we get it compiling...

----

I am curios what prompted your interest in trying `vonuvoli`?

**Comment by cipriancraciun** [comment]
I've taken a look, however it seems I have to update some libraries, which have made API incompatible changes...

Thus it'll take me some while to fix the code and make it build again.

I'll keep you posted.

**Comment by cipriancraciun** [comment]
OK, so things are somewhat "complicated"...  :)

I've managed to build the code with Rust 1.58+ nightly;  it can also be built with the stable edition, but you need to "trick" the compiler with `RUSTC_BOOTSTRAP=1`...

In short, after checking out the latest `development` commit, you can run the following:
~~~~
RUSTC_BOOTSTRAP=1 cargo build --bin vonuvoli-scheme --release
~~~~

This will result in `./target/release/vonuvoli-scheme`.

**Please note I've built it on Linux**, and as such it might not work on OSX.

----

You can invoke that as:
~~~~
./target/release/vonuvoli-scheme interpreter - ./examples/examples--transcript.ss
~~~~

The `interpreter` and `-` are mandatory, and the `.ss` is a Scheme file.  (It doesn't yet support modules, and everything that is supported is already in the top context.)

You can see everything supported by running:
~~~~
./target/release/vonuvoli-scheme reports r7rs definitions
./target/release/vonuvoli-scheme reports libraries definitions
~~~~

**Comment by cipriancraciun** [comment]
I'm closing this issue for the moment.

If it still fails to build, please reopen it.

**Comment by cipriancraciun** [comment]
Just wanted to note that the `RUSTC_BOOTSTRAP` "hack" doesn't work anymore with Rust 1.59+.  (The code compiles, but apparently some things are broken in the static build...)

Therefore Rust nightly is required, for example by using `rustup`;  once it is installed it can be invoked as:
~~~~
cargo +nightly build --bin vonuvoli-scheme --release
~~~~

**Comment by cipriancraciun** [comment]
Scratch my previous issue regarding the `RUSTC_BOOTSTRAP` workaround not working.  The issue was due to something else I use for custom builds.

The previous snippet should work:
~~~~
RUSTC_BOOTSTRAP=1 cargo build --bin vonuvoli-scheme --release
~~~~

(It now requires the latest Rust 1.59.)
